sudo: false

language: python

python:
  - "2.7"
  - "3.5"

services: postgresql

before_install:
  - export YOURAPPLICATION_MODE=TESTING

install:
  - "pip install -r requirements.txt"

before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/fhe.py"
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - export FLASK_DEBUG=1

script:
  - pytest --doctest-modules --cov=app --cov-report term-missing tests/

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - mail@stefankasberger.at
    on_success: never
    on_failure: always
