sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

services: postgresql

install:
  - "pip install -r requirements.txt"

before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/fhe.py"
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - export FLASK_DEBUG=1

script:
  - pytest --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

notifications:
  email:
    recipients:
      - mail@stefankasberger.at
    on_failure: always

after_success:
  - coveralls
