sudo: false

language: python

python:
  - "2.7"
  - "3.5"

services: postgresql

install:
  - "pip install -r requirements.txt"

before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/fhe.py"
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - export FLASK_DEBUG=1
  - export APPLICATION_MODE="TESTING"
  - export TRAVIS=True

script:
  - pytest tests/ --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - mail@stefankasberger.at
    on_failure: always
