language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

services: postgresql

install:
  - "pip install -r requirements.txt"

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - python src/manage.py migrate --noinput

script:
  - pytest

notifications:
  email:
    recipients:
      - mail@stefankasberger.at
    on_failure: always
